# Generated by Django 4.1.3 on 2023-03-29 16:15

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='url',
            field=models.TextField(blank=True, default='', max_length=builtins.max, null=True),
        ),
    ]
