# Generated by Django 4.1.3 on 2023-03-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_navbar_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navbar',
        ),
    ]
