# Generated by Django 4.1.3 on 2023-03-29 16:17

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_navbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, default='', max_length=builtins.max, null=True)),
                ('img_thanks', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
