# Generated by Django 4.1.3 on 2023-03-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_navbar_url_navbar_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navbar',
            old_name='img_thanks',
            new_name='name',
        ),
    ]
