# Generated by Django 4.1.3 on 2023-03-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_img_thanks_navbar_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
