# Generated by Django 4.1.3 on 2023-03-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
