# Generated by Django 4.1.3 on 2023-04-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_wish_delete_album_delete_bandg_delete_demo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('number', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
