# Generated by Django 4.1.3 on 2023-05-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirm',
            name='number',
        ),
        migrations.AddField(
            model_name='confirm',
            name='isGroomSide',
            field=models.BooleanField(default=True),
        ),
    ]
