# Generated by Django 4.1.3 on 2023-05-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_confirm_number_confirm_isgroomside'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirm',
            name='number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
